# Generated by Django 4.0.2 on 2022-02-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('plate', models.CharField(max_length=9, unique=True)),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
                'db_table': 'cars',
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['plate'], name='cars_plate_b92a47_idx'),
        ),
    ]
