FROM python:3.8

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get upgrade
RUN apt-get install -y  default-libmysqlclient-dev


WORKDIR /code
COPY backend/full_stack_dev_project/requirements.txt /code
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt
