FROM python:3.8

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get upgrade
RUN apt-get install -y  default-libmysqlclient-dev gcc python3-dev netcat


WORKDIR /code
COPY backend/requirements.txt /code
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt
